- name: play level variables
  hosts: local
  connection: local
  vars_file:
    - vars.yaml
  tasks:
    - name: print the variables
      vars:
        COURSE: "DEVOPS WITH AZURE"
      ansible.builtin.debug:
        msg: "i have enrolled in {{ COURSE}} course, and my trainer name is {{ TRAINER}} course duration is {{ DURATION}} "
