- name: data types in ansible
  hosts: local
  connection: local
  vars:
    IS_LIVE: false
  tasks:
    - name: print the data types in screen
      ansible.builtin.debug:
        msg: "yes the class is liveclass"
      when: IS_LIVE
