- name: install different packages
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: installing multiple softwares using loops
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{item.state }}"
      loop:
        - { name: "nginx", state: "absent" }
        - { name: "mysql", state: "absent" }
        - { name: "zip", state: "present" }
